# Welcome - Python Workshop 1 

With Tom Hohenstein 


### At the end you should be able to: 

+ create variables and check their data type 
+ identify 3 data types (and know there are others) 
+ how to import a python library
+ load a data set  
+ how to slice a numpy array  
+ how to call a function 

#### Getting setup 

+ Install Anaconda 
+ Download data  
+ Move data to desktop
+ Launch Jupyter Notebook


## Variables 

While python can be a useful calculator, it in using variables that we start "powering up" our work. 



In [1]:
print(3+8) 
x = 3+9 # use the = to assign variables 
print(x**2) 

11
144


In [3]:
print('hello')

hello


In [16]:
#
# This cell is skipped 
#

# Some quick math syntax 

a = 4
b = 6

# addition 
print(a+b)

# subtraction 
print(b-a)

# multiplication 
print(a*b)

# division 
print(a/b)

# modulo 
print(b%a)

10
2
24
0.6666666666666666
2


In [2]:
## Print command and variables 

weight_kg = 60.0
weight_kg_text = 'weight in kilograms:'

## printing multiple variables 
print(weight_kg_text, weight_kg)


weight in kilograms: 60.0


In [3]:
## do math inside of print()

print('weight in pounds:', 2.2 * weight_kg)

## and our variable is not changed! 
print(weight_kg)

weight in pounds: 132.0
60.0


In [4]:
## (re)assign a variable 
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)

weight in kilograms is now: 65.0


In [6]:
## Variables are like bins 
weight_lb = 2.2 * weight_kg # assign weight_lb 
print(weight_kg_text, weight_kg, "and in pounds:", weight_lb)

weight in kilograms: 65.0 and in pounds: 143.0


In [7]:
weight_kg = 100.0
print('weight in kilograms is now;', weight_kg, 
      'and weight in poounds is still:', weight_lb)

# note that weight in pounds has not changed 

weight in kilograms is now; 100.0 and weight in poounds is still: 143.0


## Loading data 

To load our data set on inflammation data we need to 
import a library called Numpy. 

In [4]:
import numpy 

In [15]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [16]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(data)


[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]
<class 'numpy.ndarray'>


### Information about data 

In [22]:
# let's see what 'type' our variable data is
print(type(data))

# and what type of data is within our variable (attribute)
print(data.dtype)

# and the shape of our array (attribute)
print(data.shape)

<class 'numpy.ndarray'>
float64
(60, 40)


#### Accessing individual data points by index 

In [24]:
print('first value in data:', data[0,0])

print('middle value in data:', data[30,20])

first value in data: 0.0
middle value in data: 13.0


http://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.png

#### Slicing data to select sections

In [52]:
## from data - 
###   select rows 0, 1, 2, 3 
###   and columns 0, 1, 2 ... 9
 
print(data[0:4, 0:10])

### Note that row 4 and column 10 
### are not included

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


#### Slice from different locations 

In [51]:
print(data[5:10, 1:10])

[[ 0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 1.  1.  2.  1.  3.  5.  3.  5.  8.]]


#### You can drop the upper and lower limit 
(if you want)

In [32]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]


#### Arrays know how to perform common math 

In [33]:
doubledata = small * 2

In [35]:
print('original:')
print(small)
print('doubledata:')
print(doubledata)

original:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
doubledata:
[[ 4.  6.  0.  0.]
 [ 2.  2.  0.  2.]
 [ 4.  4.  2.  2.]]


#### Math with same shaped arrays 

In [49]:
tripledata = small + doubledata
print(small)
print (' ---- ')
print(doubledata)
print (' ---- ')
print(tripledata)

[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
 ---- 
[[ 4.  6.  0.  0.]
 [ 2.  2.  0.  2.]
 [ 4.  4.  2.  2.]]
 ---- 
[[ 6.  9.  0.  0.]
 [ 3.  3.  0.  3.]
 [ 6.  6.  3.  3.]]


#### NumPy can do more! 

In [39]:
print(numpy.mean(data))

## note that .mean is a function 
## that can take an array as an argument

6.14875


### Not all functions need arguments

In [45]:
import time 
print(time.ctime())

## note that you still need the () 
## to call the function

Fri Sep 21 08:20:07 2018


### More NumPy functions

In [42]:
maxval = numpy.max(data) # find the max value
minval = numpy.min(data) # find the min value
stdval = numpy.std(data) # find the standard deviation

print('max inflammation:', maxval)
print('min inflammation:', minval)
print('standard deviation', stdval)

max inflammation: 20.0
min inflammation: 0.0
standard deviation 4.61383319712


#### Another way to assign variables 

In [44]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print(maxval, minval, stdval)


20.0 0.0 4.61383319712


#### Finding Functions 

In [54]:
## use autocomplete 
numpy.ab

In [55]:
numpy.mean?