# Welcome - Python Workshop 1 

With Tom Hohenstein 


### At the end you should be able to: 

+ create variables and check their data type 
+ identify 3 data types (and know there are others) 
+ how to import a python library
+ load a data set  
+ how to slice a numpy array  
+ how to call a function 

#### Getting setup 

+ Install Anaconda - https://www.anaconda.com/download/#macos
+ Download data  - http://swcarpentry.github.io/python-novice-inflammation/setup/
+ Move data to desktop
+ Launch Jupyter Notebook 


### Quick overview of Jupyter Notebooks 


## Variables 

While python can be a useful calculator, it in using variables that we start "powering up" our work. 



In [14]:
x = 3+9
print(x)

12


### Print command and variables 



In [17]:
weight_kg = 60.0
weight_kg_text = "weight in kilograms:"

print(weight_kg_text, weight_kg) 

weight in kilograms: 60.0


### do math inside of print()



In [18]:
print("weight in pounds:", 2.2*weight_kg)

weight in pounds: 132.0


### (re)assign a variable 


In [22]:
weight_lb = 2.2 * weight_kg
print(weight_kg_text, weight_kg, "and  in pounds:", weight_lb)
weight_kg = 100
print("new weight:", weight_kg)

weight in kilograms: 100 and  in pounds: 220.00000000000003
new weight: 100


### Variables are like bins 


## Loading data 

To load our data set on inflammation data we need to 
import a library called Numpy. 

In [29]:
import numpy 
data = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=",")
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


### Information about data 

In [33]:
print(type(data))
print(data.dtype)
print(data.shape) 

<class 'numpy.ndarray'>
float64
(60, 40)


### Accessing individual data points by index 

http://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.png

In [35]:
print(data[0,0])
print(data[30,20])

0.0
13.0


### Slicing data to select sections

In [43]:
print(data[:5, :4])

[[ 0.  0.  1.  3.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  1.  3.]
 [ 0.  0.  2.  0.]
 [ 0.  1.  1.  3.]]


### Slice from different locations 

### You can drop the upper and lower limit 
(if you want)

### Arrays know how to perform common math 

In [48]:
small = data[0:3, 0:3]
print("small is:")
print(small)
doubledata = small *2
print("double")
print(doubledata)


small is:
[[ 0.  0.  1.]
 [ 0.  1.  2.]
 [ 0.  1.  1.]]
double
[[ 0.  0.  2.]
 [ 0.  2.  4.]
 [ 0.  2.  2.]]
[[ 0.  0.  3.]
 [ 0.  3.  6.]
 [ 0.  3.  3.]]


### Math with same shaped arrays 

In [49]:
tripledata = small + doubledata
print(tripledata)   

[[ 0.  0.  3.]
 [ 0.  3.  6.]
 [ 0.  3.  3.]]


### NumPy can do more! 

In [52]:
print(numpy.mean(data))
print(numpy.max(data))
print(numpy.min(data))
print(numpy .std(data))

6.14875
20.0
0.0
4.61383319712


### Not all functions need arguments

In [6]:
import time 
print(time.ctime())  


Tue Sep 25 11:22:21 2018


### More NumPy functions

In [53]:
numpy.mean?

### Another way to assign variables 

In [56]:
# naming variable 

maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)
print(maxval, minval, stdval)

20.0 0.0 4.61383319712



### Finding Functions 

In [54]:
## use autocomplete and ? 
